// This file is auto-generated by scripts/generate-native.ts
// DO NOT EDIT MANUALLY — changes will be overwritten on the next build
// To update: modify the source in src/icons/*.tsx, src/illustrations/*.tsx, or src/brand/*.tsx, then run `yarn build`

import { Circle, Defs, Path, RadialGradient, Rect, Stop, Svg } from 'react-native-svg';

import type { IBrandIconProps } from '../../types/brand.native';

export default function IconInstagram({ size = 24, ...props }: IBrandIconProps) {
  return (
    <Svg width={size} height={size} fill="none" viewBox="0 0 24 24" {...props}>
      <Rect x="2" y="2" width="20" height="20" rx="5" fill="url(#instagram_filled_gradient)" />
      <Path
        d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"
        stroke="white"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <Circle cx="17.5" cy="6.5" r="1" fill="white" />
      <Defs>
        <RadialGradient
          id="instagram_filled_gradient"
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(4.8 22.8) rotate(-55.4) scale(24.6)"
        >
          <Stop stopColor="#FDF497" />
          <Stop offset="0.05" stopColor="#FDF497" />
          <Stop offset="0.45" stopColor="#FD5949" />
          <Stop offset="0.6" stopColor="#D6249F" />
          <Stop offset="0.9" stopColor="#285AEB" />
        </RadialGradient>
      </Defs>
    </Svg>
  );
}
