// This file is auto-generated by scripts/generate-native.ts
// DO NOT EDIT MANUALLY — changes will be overwritten on the next build
// To update: modify the source in src/icons/*.tsx, src/illustrations/*.tsx, or src/brand/*.tsx, then run `yarn build`

import { Circle, ClipPath, Defs, G, Path, Rect, Svg } from 'react-native-svg';

import type { IBrandIconProps } from '../../types/brand.native';

export default function IconNaver({ size = 24, ...props }: IBrandIconProps) {
  return (
    <Svg width={size} height={size} fill="none" viewBox="0 0 24 24" {...props}>
      <Circle cx="12" cy="12" r="9.9" fill="#00C73C" />
      <G clipPath="url(#clip0_naver)">
        <Path
          d="M13.7797 12.3521L10.0726 7H6.99927V17H10.2184V11.6483L13.9259 17H16.9993V7H13.7797V12.3521Z"
          fill="white"
        />
      </G>
      <Defs>
        <ClipPath id="clip0_naver">
          <Rect width="10" height="10" fill="white" transform="translate(6.99927 7)" />
        </ClipPath>
      </Defs>
    </Svg>
  );
}
