name: "Chromatic"
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: yarn
      - name: Generate design tokens
        run: |
          yarn token-transform
          yarn token-build
      - name: Build packages
        run: yarn build
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
