name: PR Review Notification

on:
  pull_request:
    types: [opened, ready_for_review]
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request) ||
      (github.event_name == 'pull_request_review') ||
      (github.event_name == 'pull_request_review_comment')
    steps:
      - uses: actions/checkout@v4
      - uses: datepop/notify-pr-review@v1.2.0
        with:
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          user_mappings: ${{ secrets.USER_MAPPINGS }}